import type { PullRequest } from "@/lib/types/pull-request.types";

// Titik acuan tetap (bukan Date.now() dievaluasi ulang) supaya timestamp
// dummy identik antara render server dan client — Date.now() langsung di
// sini akan menghasilkan nilai berbeda tiap kali modul di-evaluate ulang
// (server lalu client saat hydration), memicu hydration mismatch pada teks
// hasil formatRelativeTime.
const NOW = new Date("2026-09-21T10:00:00.000Z").getTime();
const MINUTE = 60 * 1000;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

export const DUMMY_PULL_REQUESTS: PullRequest[] = [
  {
    id: "pr-1",
    title: "Fix race condition in webhook retry queue",
    number: "#482",
    source: "github",
    repository: "critiq-fe",
    targetBranch: "main",
    author: "dinda.p",
    criticalCount: 2,
    reviewMode: "ai_assisted",
    status: "changes_requested",
    updatedAt: new Date(NOW - 26 * MINUTE).toISOString(),
  },
  {
    id: "pr-2",
    title: "Add pagination to activity log endpoint",
    number: "!128",
    source: "gitlab",
    repository: "critiq-api",
    targetBranch: "develop",
    author: "raka.s",
    criticalCount: 0,
    reviewMode: "manual",
    status: "approved",
    updatedAt: new Date(NOW - 2 * HOUR).toISOString(),
  },
  {
    id: "pr-3",
    title: "Implement branch multi-select for onboarding wizard",
    number: "#491",
    source: "github",
    repository: "critiq-fe",
    targetBranch: "develop",
    author: "ilham.d",
    criticalCount: 0,
    reviewMode: "ai_assisted",
    status: "open",
    updatedAt: new Date(NOW - 4 * MINUTE).toISOString(),
  },
  {
    id: "pr-4",
    title: "Refactor scan queue worker to use bulk insert",
    number: "!134",
    source: "gitlab",
    repository: "critiq-scanner",
    targetBranch: "main",
    author: "wulan.k",
    criticalCount: 5,
    reviewMode: "manual",
    status: "changes_requested",
    updatedAt: new Date(NOW - 3 * DAY).toISOString(),
  },
  {
    id: "pr-5",
    title: "Update dependency versions for security patch",
    number: "#498",
    source: "github",
    repository: "critiq-fe",
    targetBranch: "main",
    author: "bagas.n",
    criticalCount: 0,
    reviewMode: "manual",
    status: "approved",
    updatedAt: new Date(NOW - 1 * DAY).toISOString(),
  },
  {
    id: "pr-6",
    title: "Add rate limiting middleware for public API",
    number: "!140",
    source: "gitlab",
    repository: "critiq-api",
    targetBranch: "main",
    author: "dinda.p",
    criticalCount: 1,
    reviewMode: "ai_assisted",
    status: "open",
    updatedAt: new Date(NOW - 45 * MINUTE).toISOString(),
  },
  {
    id: "pr-7",
    title: "Fix flaky test in repository connection flow",
    number: "#503",
    source: "github",
    repository: "critiq-fe",
    targetBranch: "develop",
    author: "raka.s",
    criticalCount: 0,
    reviewMode: "manual",
    status: "open",
    updatedAt: new Date(NOW - 6 * HOUR).toISOString(),
  },
  {
    id: "pr-8",
    title: "Improve error messages for GitLab token verification",
    number: "!145",
    source: "gitlab",
    repository: "critiq-scanner",
    targetBranch: "develop",
    author: "wulan.k",
    criticalCount: 3,
    reviewMode: "ai_assisted",
    status: "changes_requested",
    updatedAt: new Date(NOW - 20 * HOUR).toISOString(),
  },
  {
    id: "pr-9",
    title: "Add dark mode toggle to settings page",
    number: "#511",
    source: "github",
    repository: "critiq-fe",
    targetBranch: "main",
    author: "bagas.n",
    criticalCount: 0,
    reviewMode: "manual",
    status: "approved",
    updatedAt: new Date(NOW - 5 * DAY).toISOString(),
  },
];
